version: 2.1
description: Life Game Builds

executors:
  docker-executor:
    docker:
      - image: 'cimg/openjdk:11.0.13'

orbs:
  maven: circleci/maven@1.3

jobs:
  install-libraries:
    executor: docker-executor
    steps:
      - run:
          name: updating
          command: sudo apt-get update
      - run:
          name: install libpangoft2-1.0-0
          command: sudo apt-get install libpangoft2-1.0-0

workflows:
  tests:
    jobs:
      - install-libraries
      - maven/test:
          command: '-P test-headless,os-linux verify'
          executor: docker-executor
