version: 2.1
description: Life Game Builds

orbs:
  maven: circleci/maven@1.3

workflows:
  tests:
    jobs:
      build:
        docker:
          - image: cimg/openjdk:11.0.13
        steps:
          - run: sudo apt-get update
          - run: sudo apt-get install libpangoft2-1.0-0
          - maven/test:
              command: '-P test-headless,os-linux verify'