version: 2.1
description: Life Game Builds

executors:
  docker-executor:
    docker:
      - image: 'cimg/openjdk:11.0.13'

orbs:
  maven: circleci/maven@1.3

workflows:
  tests:
    jobs:
      build:
        executor: docker-executor
