version: 2.1
description: Life Game Builds

executors:
  java11-executor:
    docker:
      - image: 'cimg/openjdk:11.0'

orbs:
  maven: circleci/maven@1.3

workflows:
  "Tests":
    jobs:
      - maven/test:
          command: '-P test-headless verify'
          executor: java11-executor